config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'

  get 'welcome/about'

  get 'welcome/news'

  get 'welcome/schedule'

  get 'welcome/classes'

  get 'welcome/fees'

  get 'welcome/registration'

  get 'welcome/gallery'

  get 'welcome/contact'

  root "welcome#home"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def news
  end

  def schedule
  end

  def classes
  end

  def fees
  end

  def registration
  end

  def gallery
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yashs Didi's Dance School</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <div class="container"> -->
    <!-- <ul class="nav nav-tabs"> -->
     <!-- <%= image_tag("cover.jpg", :alt => "cover") %> -->
     <!-- <li> -->
       <%= link_to "Home", welcome_home_path %>
     <!-- </li> -->
     <!-- <li><%= link_to "Gallery", welcome_gallery_path %></li> -->
     <!-- <li> -->
     <%= link_to "About Yashs", welcome_about_path %>
     <%= link_to "Registration", welcome_registration_path %>
       <%= link_to "Events", welcome_news_path %>
     <!-- </li> -->
     <!-- <li><%= link_to "Classes", welcome_classes_path %></li> -->
     <!-- <li><%= link_to "Fees", welcome_fees_path %></li> -->
     <!-- <li><%= link_to "Schedule", welcome_schedule_path %></li> -->
     <!-- <li> -->
     <!-- </li>
     <li> -->
     <!-- </li>
     <li> -->
       <%= link_to "Contact Us", welcome_contact_path %>
     <!-- </li> -->

   <!-- </ul> -->
 <!-- </div> -->
<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<!-- <h1>About Nachle With Yashs Didi</h1> -->
<!-- <p>Find me in app/views/welcome/about.html.erb</p> -->
<!-- <p>Find us on <a href="https://www.facebook.com/nwydds/">Facebook</a>!</p> -->
<!-- Our Mission is to spread a cultural awareness to the community and empower </br>
children with the skills and fortitude that an in-depth dance school </br> -->
<!-- can bring. -->
 
<%= image_tag("about.jpg", :alt => "profile") %>

app/views/welcome/classes.html.erb
<h1>Welcome#classes</h1>
<!-- <p>Find me in app/views/welcome/classes.html.erb</p> -->


My Chance to Dance for ages 2.5 - 3.5

A Yash Studio original!  This wonderful class is designed for children who want </br>
to dance but are not quite old enough to join a ballet class.  The instructor</br>
 uses games, stories, and songs to teach balance, rhythm, movement, coordination, </br>
 and basic ballet steps. This class does not perform in the Spring Recital, but does</br>
  participate in Parents’ Observation Week.</br>

app/views/welcome/contact.html.erb
<!-- <h1>Welcome#contact</h1> -->
<!-- <p>Find me in app/views/welcome/contact.html.erb</p> -->
<!-- <p>

<strong>Phone</strong>: (860) 266-6573 </p>

<p>

<strong>E-mail</strong>: <a href="mailto:nwydds@gmail.com">nwydds@gmail.com</a>

</p>

<p>

<strong>Location</strong>:<br />


133 Wilson St
<br />

Hartford, Connecticut 06106</p>
<p><strong>Map to studio</strong>:</p>
<p align="center">
  133 Wilson St
  Hartford, Connecticut 06106<br>
(860) 266-6573</p> -->
<%= image_tag("contact.jpg", :alt => "profile") %>

app/views/welcome/fees.html.erb
<h1>Welcome#fees</h1>
<!-- <p>Find me in app/views/welcome/fees.html.erb</p> -->

app/views/welcome/gallery.html.erb
<h1>Welcome#gallery</h1>
<!-- <p>Find me in app/views/welcome/gallery.html.erb</p> -->

app/views/welcome/home.html.erb
<!-- <h1>Welcome#home</h1> -->
<!-- <p>Find me in app/views/welcome/home.html.erb</p> -->
<%= image_tag("homepage.jpg", :alt => "profile") %>

app/views/welcome/news.html.erb
<!-- <h1>Welcome#news</h1> -->
<!-- <p>Find me in app/views/welcome/news.html.erb</p> -->
<%= image_tag("events.jpg", :alt => "profile") %>

app/views/welcome/registration.html.erb
<!-- <h1>Welcome#registration</h1> -->
<!-- <p>Find me in app/views/welcome/registration.html.erb</p> -->
<form action="https://getsimpleform.com/messages?form_api_token=1702c7ddd79f7beac9172aa44ba5b6b3"
    method="post">
    <!-- the redirect_to is optional, the form will redirect to the referrer on submission -->
    <!-- <input type='hidden' name='redirect_to' value='<the complete return url e.g. http://fooey.com/thank-you.html>'/> -->
    <p class="register" style="margin-bottom: 0in; line-height: 100%">
      <span style="text-decoration: none">Parent Name<br>First
        <input type='text' name='Parent First Name' /><br>Last
        <input type='text' name='Parent First Name' />
      </span>
    </p>
    <p class="register" style="margin-bottom: 0in; line-height: 100%">
      <span style="text-decoration: none">Email
        <input type='text' name='Email' />
      </span>
    </p>
    <p class="register" style="margin-bottom: 0in; line-height: 100%">
      <span style="text-decoration: none">Phone Number
        <input type='text' name='PhoneNum' />
      </span>
    </p>
    <p class="register" style="margin-bottom: 0in; line-height: 100%">
      <span style="text-decoration: none">Age of student
        <input type='text' name='StudentAge' />
      </span>
    </p>
    <p class="register" style="margin-bottom: 0in; line-height: 100%">
      <input type='submit' value='Submit' /> </form>

      <%= image_tag("registration.jpg", :alt => "profile") %>
<!-- <a href="studio_policy_and_procedures.pdf">Studio Policy and Procedures</a><br> -->
<!-- <a href="waiver_and_release_from_liability_form.pdf">Waiver and Release from Liability Form</a><br><br><br><br><br><br> -->

app/views/welcome/schedule.html.erb
<h1>Welcome#schedule</h1>
<!-- <p>Find me in app/views/welcome/schedule.html.erb</p> -->